### PR TITLE
Add multi line comment syntax

### PR DESCRIPTION
**Pull request by imaqtkatt**

### CODE REVIEW

**Comment by developedby** [comment]
Closes #595

**Review by developedby — COMMENTED** [review]
I'm not sure about `#{ }#`.
I understand why but it just looks so ugly.

**Comment by imaqtkatt** [comment]
I slightly would prefer `#{ ... #}` over `#{ ... }#`, what do you think?

**Comment by developedby** [comment]
Every language does this differently, there isn't any common way to do it other than `/* */`.

If i were to choose, I'd go with `#= =#` like in julia, even if it doesn't look like it's opening a block, or with `#[ ]#` like in nim, even if we don't really use `[ ]` with this kind of meaning elsewhere.

Relevant: https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(syntax)#Comment_comparison

Do you have any preference or reason for any of the options? If not, we'll keep `#{ }#`

> I slightly would prefer `#{ ... #}` over `#{ ... }#`, what do you think?

I like it

**Comment by developedby** [comment]
Does this also fix https://github.com/HigherOrderCO/Bend/issues/623 ?

**Comment by imaqtkatt** [comment]
Yes, it does fix the issue

**Review by developedby — APPROVED** [review]

**Pull request merged**
