### PR TITLE
#598 Add file IO flush function

### PR DESCRIPTION
**Pull request by bhavik-goplani**
Solves #598  

I had a little difficulty testing. This runs without bugs but doesn't write to the file when I run my bend program. Am I missing something here? I also built both bend and hvm from the main branch.
```
def main:
  file = IO/FS/open("file.txt", "w+")
  data = "Hello, World!"
  write = IO/FS/write(file, data)
  flush = IO/FS/flush(file)
  close = IO/FS/close(file)
  return 0
```

### CODE REVIEW

**Review by developedby — APPROVED** [review]

**Comment by developedby** [comment]
Have you run you program using `bend run`, `bend run-c` or `bend run-cu`?

Also, you have to rebase your PR because there's a minor conflict

**Comment by bhavik-goplani** [comment]
I ran the program using `bend run` and `bend run-c`
Yep, I'll rebase the PR. Thanks for the feedback!

**Comment by developedby** [comment]
`bend run` doesn't have IO, only `run-c` and `run-cu`.

**Comment by developedby** [comment]
Thank you for your contribution!

**Comment by bhavik-goplani** [comment]
I'll try `run-c` again. Of course, I am happy to contribute. I'll pick another issue after this if that works with you.

**Comment by bhavik-goplani** [comment]
I got the script to work and flush also works as expected.
```
def main:
  with IO:
    fd <- IO/FS/open("file.txt", "w")
    data = [72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33]
    write <- IO/FS/write(fd, data)
    flush <- IO/FS/flush(fd)
    write <- IO/FS/write(fd, data)
    write <- IO/FS/write(fd, data)
    close <- IO/FS/close(fd)
    return close
```

**Pull request merged**
