### PR TITLE
Add text version of demo

### PR DESCRIPTION
**Pull request by Jacob-Lockwood**
Add text version of demo, for accessibility and just general usefulness. People I showed Bend to complained that the video was inconvenient, and I agree. I still linked to the Twitter post if anyone prefers that.

### CODE REVIEW

**Review by anplumbing23 — APPROVED** [review]

**Review by antonkesy — APPROVED** [review]
Great addition ^^ LGTM

**Comment by developedby** [comment]
This is a bit hard to decide because there are people who will prefer both versions.
I'll definitely add the text version as well, but I don't know which will be the main one

**Comment by kings177** [comment]
i think we should keep the video where it is, but add in the footer of it something like "read the whole transcription here", linking to the text version.

**Comment by anplumbing23** [comment]
What is this

**Comment by Jacob-Lockwood** [comment]
I think linking to the video is better than linking to the text transcription because if I just opened the Bend repo to look at the readme, I don’t want to start reading and then immediately get hit with a 2-minute-long GIF I can’t pause or skip forward in. It’s quite difficult to mentally parse the code on screen or the benchmarks that show up when they’re only on screen for a few seconds.

On the flip side, with the text version, if I don’t care about the code and just want the benchmarks, I can just scroll past that part and be done.

**Comment by developedby** [comment]
The demo was removed in #547

**Pull request closed without merging**
