### PR TITLE
Add License to BEND

### PR DESCRIPTION
**Pull request by Sipher**
Added Apache 2.0 License, increased version and changed the description

New version - 0.2.7

New description - "A parallel language" <- Reverted

### CODE REVIEW

**Comment by developedby** [comment]
Why did you change the description of the package?

**Comment by Sipher** [comment]
I understood that Taelin wants the  description to be "A parallel language", Just like in the website, I might have misunderstood, if so, I can change back to the old one.

**Comment by kings177** [comment]
> Why did you change the description of the package?

We are trying to keep the wording of things the same throughout every place we mention anything, and since we are now describing Bend as "A parallel language", we should apply this to everything else.

**Comment by developedby** [comment]
That's so ambiguous and not meaningful. You have to imagine that people will see this description without the context of the website and other stuff

**Comment by kings177** [comment]
hmmm, what do you propose?

**Comment by developedby** [comment]
I think the current description is fine, and it matches the description of the hvm repo right now

**Comment by Sipher** [comment]
Reverted the description to the old one, kept the version updated and added the license.

**Comment by developedby** [comment]
Closes #325

**Pull request merged**
