### PR TITLE
Add nushell completions for bend

### PR DESCRIPTION
**Pull request by OJarrisonn**
Create a script that adds nushell completions for bend

To use the script install nushell >= 0.93 and `source` it from your config.nu

### CODE REVIEW

**Comment by developedby** [comment]
Thank you very much for your contribution!
But I'd rather keep utils in a separate repository.
Do you want to put this in your own github account and I'll link to it in the documentation?

**Comment by OJarrisonn** [comment]
I also commited this script in the official nushell/nu_scripts repo, this may be a more appropriate place.

Here is the link https://github.com/nushell/nu_scripts/tree/main/custom-completions/bend

Feel free to add it to the docs

**Comment by developedby** [comment]
I'll close the PR then. I have to figure out the best way of listing the existing tooling for Bend devs

**Comment by developedby** [comment]
For now it's here https://github.com/HigherOrderCO/Bend/issues/452. Later we'll move it somewhere with more visibility

**Pull request closed without merging**
